#!/usr/bin/php
<?php
$lastport="";
$lastallips="";
@unlink("root/nft/.cache");
@unlink("root/nft/.ruleset");
$rulehead="flush ruleset\ntable ip nat {\nchain prerouting {\ntype nat hook prerouting priority 0; policy accept;\n";
$rulefoot="}\nchain postrouting {\ntype nat hook postrouting priority 0; policy accept;\nmasquerade\n}\n}\n";

$ipmapstr="";
$portmapstr="";
$stdin = fopen('php://stdin', 'r');
$cachefile = fopen("/root/nft/.cache",'w');
$ruleset = fopen("/root/nft/.ruleset",'w');
if(!is_resource($ruleset) || !is_resource($stdin) || !is_resource($cachefile)) {echo "Something Unexpected happened\n";goto cls;}
fwrite($ruleset,$rulehead);
    while (($buffer = fgets($stdin, 4096)) !== false) {
        if(strpos($buffer,'-A PREROUTING -s ')!==false){
			$barr=explode(" ",$buffer);
//cachefile related
			$allips=explode(",",$barr[3]);
			$dr=explode(":",$barr[13]);
			fwrite($cachefile,$barr[9]." ".$dr[0]." ".trim($dr[1])." ".substr(trim($barr[17]),1,-1)." 0");
			foreach($allips as $ip) fwrite($cachefile," ".$ip);
			fwrite($cachefile,"\n");
//ruleset related
			if($lastallips!=$barr[3]){
				if($lastallips!=""){
					fwrite($ruleset,"tcp dport ".$sport."-".$lastport." ip saddr {".$lastallips."} dnat tcp dport map {".rtrim($ipmapstr,",")."} : tcp dport map {".rtrim($portmapstr,",")."}\n");
				}
				$sport=$barr[9];
				$ipmapstr="";
				$portmapstr="";
			}
			$ipmapstr .= $barr[9].":".$dr[0].",\n";
			$portmapstr .= $barr[9].":".trim($dr[1]).",\n";
			$lastallips = $barr[3];
			$lastport = $barr[9];
         }
    }
    if (!feof($stdin))echo "Error: unexpected fgets() fail\n";
if($ipmapstr!="")fwrite($ruleset,"tcp dport ".$sport."-".$lastport." ip saddr {".$lastallips."} dnat tcp dport map {".rtrim($ipmapstr,",\n")."} : tcp dport map {".rtrim($portmapstr,",\n")."}\n");
fwrite($ruleset,$rulefoot);
cls:
if(is_resource($ruleset))fclose($ruleset);
if(is_resource($stdin))fclose($stdin);
if(is_resource($cachefile))fclose($cachefile);
exec("nft -f /root/nft/.ruleset");

exec("sysctl -w net.netfilter.nf_conntrack_tcp_loose=0");
exec("sysctl -w net.netfilter.nf_conntrack_tcp_timeout_time_wait=1");
exec("sysctl -w net.netfilter.nf_conntrack_tcp_timeout_established=120");
?>